### PR TITLE
Add a couple of viz tool and tutorial links

### PR DESCRIPTION
**Pull request by rsignell-usgs**
Adding links to PyViz and EarthSim

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks for this! I edited your branch to add links to the individual pyviz sub-components, as I think they are awesome enough to call out specifically.

**Comment by rabernat** [comment]
I don't know why geo.holoviews.org is being flagged as duplicate

**Comment by rsignell-usgs** [comment]
If we are listing the various awesome pyviz components, let's include [hvplot](https://hvplot.pyviz.org/) as well

**Comment by philippjfr** [comment]
>I don't know why geo.holoviews.org is being flagged as duplicate

geoviews.org is the canonical address, I should probably make geo.holoviews.org forward to that instead.

**Pull request merged**
